``` {r}
#This script is to extract the data of the BC on pvm from salicylate treated experiment in 24hpi. There were three dataset with 23, 24 & 25 hpi timepoints. The results were obtained by using the macro "BC_PVM_salicylate_Nov17.ijm".
```

``` {r}
library(ggplot2)
library(dplyr)
library(magrittr)
```

``` {r}
#Declaring the path
base_path <- "/home/lab-admin/LAKSHMI/Salicylate_BConPVM_analysis/"

#Listing the folders list
folder_list <-
  c(
    "20161020_salicylate_23hpi_BC_PVM_results",
    "20161024_salicylate_24hpi_BC_PVM_results",
    "20161028_salicylate_25hpi_BC_PVM_results"
  )

folder_tre_untre_list <-
  c(
    "Treated_BCPVM_results",
    "Untreated_BCPVM_results"
  )
```

``` {r}
loca_pvm <- list(list())
pvm <- list(list())

for (m in 1:length(folder_list))
{
  path <- sprintf("%s%s", base_path, folder_list[m])
  
  
  for (p in 1:length(folder_tre_untre_list)){
    path_final <- sprintf("%s/%s", path, folder_tre_untre_list[p])
    print(path_final)
    file_timepoint <- list.dirs(path_final)
    
    file_timepoint <- file_timepoint[-1]
    
    for (j in 1:length(file_timepoint)){
      files_csv_list <-
        c(
          "statistics_PVM_surfacearea_BC.csv",
           "statistics_PVM.csv"
         )
      dat_pvm <- list()
      for (i in 1:length(files_csv_list)){
         dat_pvm[[i]] <- readr::read_csv(sprintf("%s/%s", file_timepoint[j], files_csv_list[[i]]))
      }
      
      names(dat_pvm) <- files_csv_list
      dat_pvm_vol <- dat_pvm[grep("PVM.csv", names(dat_pvm))]
      dat_pvm_vox <- dat_pvm[grep("PVM.csv", names(dat_pvm))]
      dat_saBC_pvm <- dat_pvm[grep("surfacearea_BC", names(dat_pvm))]
      dat_saBC_int_intensity_pvm <- dat_pvm[grep("surfacearea_BC", names(dat_pvm))]
      
      if (dat_saBC_pvm %>% as.data.frame() %>% nrow() == 0) {
        dat_saBC_pvm[[1]][1,] <- 0 
        dat_saBC_pvm[[1]] <- plyr::colwise(as.numeric)(dat_saBC_pvm[[1]])
    }
    
    loca_pvm[[j]] <-
      cbind(
        lapply(dat_pvm_vol, function(x) x[[2]]) %>% as.matrix(),
        lapply(dat_pvm_vox, function(x) x[[5]]) %>% as.matrix(),
        lapply(dat_saBC_pvm, function(x) x[[3]] %>% as.numeric() %>% sum()/2) %>% as.matrix(),
        lapply(dat_saBC_int_intensity_pvm, function(x) x[[6]] %>% as.numeric %>% sum()) %>% as.matrix()
        
      )%>% as.data.frame()
    print(loca_pvm[[j]])
    }
    
  }
  
  tot_dat_pvm <- list(list())

  for (k in 1:length(file_timepoint)){
    tot_dat_pvm[[k]] <- rbind(loca_pvm[[k]]) %>% as.data.frame()
  }
   pvm[[m]] <- tot_dat_pvm %>% bind_rows()
}
total_pvm <- pvm %>% bind_rows()
View(total_pvm)

  
  

```






