```{r}
# Intialising the necessary library
library(ggplot2)
library(dplyr)
library(magrittr)
library(svglite)
library(grid)
library(gridExtra)
```

```{r}
#Reading the data file
dat <- readr::read_csv("/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/master_data.csv")

#dat <- readr::read_csv("/Users/lakshmibalasubramanian/Documents/Lakshmi/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/master_data.csv")

dat_uninf <- dat %>% dplyr::filter(dat$Status == "UNINF")
dat_infec <- dat %>% dplyr::filter(dat$Status == "INF")
dat_PVM <- dat %>% dplyr::filter(dat$Status == "PVM")
dat_inf_uninf <- rbind(dat_infec, dat_uninf)
dat_inf_PVM <- cbind(dat_infec,dat_PVM)
dat_24_48 <- dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint != "33hpi")
dat_24_48_PVM <- dat_PVM %>% dplyr::filter(dat_PVM$Timepoint != "33hpi")

# Adding a new column to a dataframe 
dat_inf_PVM["Ratio_Vol_CELL_PVM"] <- 0

# Computing values for new column and adding to it
dat_inf_PVM$Ratio_Vol_CELL_PVM <- dat_inf_PVM$Cell_Vol.1/dat_inf_PVM$Cell_Vol
dat_24_48$BC_SA_Vox <- dat_24_48$BC_SA_Vox/2

```

```{r}

Status1 <- factor(dat_inf_uninf$Status, levels = c('UNINF','INF'), ordered = TRUE)

#This is to change the color of the jitter points of user's choice
P <- scale_color_manual(dat_inf_uninf$Status,values = c("Turquoise4", "Red"))

#Plot for volume of the infected hepatocytes (24,33,48 hpi)

ggplot2::ggplot(dat_inf_uninf) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Cell_Vol, fill = Status1), outlier.color = NA, size = 1.0, alpha = 0.0, width = 0.4, position = position_dodge(width = 0.7), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Cell_Vol, color = Status1), cex = 2.0, alpha = 0.7, position = position_jitterdodge(0.2,0.2,0.7)) + P +
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = c(0.2,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0)) + ylab("Volume of infected hepatocytes (micron^3)") + xlab("Timepoint of infection")
  ggplot2::ggsave("volume_inf_hepatocyte1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_inf_hepatocyte1.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
#Plot for volume of the PVM (24,33,48 hpi)

ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Cell_Vol, fill = Status), outlier.color = NA, size = 1.0, alpha = 0.0, width = 0.4, position = position_dodge(width = 0.7), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Cell_Vol, fill = Status), colour = "red", cex = 2.0, alpha = 0.7, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.position = "none") + ylab("Volume of the PVM (micron^3)") + xlab("Timepoint of infection") +
  ggplot2::ggsave("volume_PVM1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_PVM1.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}
#Plot for SA (pixels) of the PVM (24,33,48 hpi)

ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, cell_Surf_Pix, fill = Status), fill = "red", alpha = 0.2, width = 0.5, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = cell_Surf_Pix, fill = Status, color = Status), colour = "Red", cex = 2.0, alpha = 0.9, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()) + ylab("Surface of PVM (pixel^2)") + xlab("Timepoint of infection") +
  ggplot2::ggsave("SA_PVM.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_PVM.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}
#Plot for SA (voxels) of the PVM (24,33,48 hpi)

P4<- ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Cell_Surf_Vox, fill = Status), outlier.color = NA, fill = "red", alpha = 0.2, width = 0.5, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Cell_Surf_Vox, fill = Status, color = Status), colour = "Red", cex = 2.0, alpha = 0.9, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()) + ylab("Surface voxels of PVM") + xlab("Timepoint of infection")
  ggplot2::ggsave("SA_Vox_PVM.png", path = "/Users/lakshmibalasubramanian/Documents/Lakshmi/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_PVM.svg", path = "/Users/lakshmibalasubramanian/Documents/Lakshmi/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}

#multiplot(P1,P2,P3,P4,cols =2)

G <- grid.arrange(P1,P2,P3,P4,widths=c(0.8, 0.8),ncol=2)

ggsave("all_graphs.png", path ="/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", plot = G, width = 8, height = 8, units = "in", dpi = 300 )

```



```{r}
#Plot for volume of the infected and uninfected cells between 24 and 48hpi

cell_dat <- dat_infec %>% group_by(Timepoint) %>% summarise_all(mean)
cell_dat$Status <- "CELL"
pvm_dat <- dat_PVM %>% group_by(Timepoint) %>% summarise_all(mean)
pvm_dat$Status <- "PVM"

pvm_dat["Normalise_volume"] <- 0
pvm_dat$Normalise_volume <- pvm_dat$Cell_Vol/408.1024
pvm_dat["Normalise_SV"] <- 0
pvm_dat$Normalise_SV <- pvm_dat$Cell_Surf_Vox/5024.60

all_dat <- rbind(cell_dat,pvm_dat)

#C <- scale_color_manual(all_dat$Status, values = c("Red"))




ggplot2::ggplot(pvm_dat) +
  
  ggplot2::geom_line(ggplot2::aes(Timepoint, pvm_dat$Normalise_volume, group = Status, color = Status),linetype =1, size=0.8, alpha = 1) +
  ggplot2::geom_point(ggplot2::aes(Timepoint, pvm_dat$Normalise_volume, group = Status, color = Status)) +
  ggplot2::geom_point(ggplot2::aes(Timepoint, pvm_dat$Normalise_SV, group = Status, color = Status)) +
  ggplot2::geom_line(ggplot2::aes(Timepoint, pvm_dat$Normalise_SV, group = Status, color = Status),linetype =2, size = 0.8, alpha = 1) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=12, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=12, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()) + ylab("Volume and SV normalised to 24hpi") + xlab("Timepoint of infection") +
  ggplot2::ggsave("combined_plot1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
  


ggplot2::ggplot(pvm_dat) +
  
  ggplot2::geom_point(ggplot2::aes(Timepoint, pvm_dat$Normalise_SV, group = Status)) +
  ggplot2::geom_line(ggplot2::aes(Timepoint, pvm_dat$Normalise_SV, group = Status),linetype =1, size = 0.8, alpha = 1) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=12, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=12, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank()) + ylab("Surface voxels of PVM normalised to 24hpi") + xlab("Timepoint of infection") +
  ggplot2::ggsave("Normalised_plot_SV_PVM.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
  


```

```{r}
#Plot for ratio between the pvm and cell volume
ggplot2::ggplot(dat_inf_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Ratio_Vol_CELL_PVM), outlier.color = NA,  size = 1.0, alpha = 0.0, width = 0.4, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Ratio_Vol_CELL_PVM, fill = Status), colour = "red", cex = 2.0, alpha = 0.7, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.position = "none") + ylab("Fraction of PVM in hepatocyte") + xlab("Timepoint of infection") +
  ggplot2::ggsave("volume_ratio_cell_PVM1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_ratio_cell_PVM1.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
Status1 <- factor(dat_24_48$Status, levels = c('UNINF','INF'), ordered = TRUE)

#This is to change the color of the jitter points of user's choice
P <- scale_color_manual(dat_24_48$Status,values = c("Turquoise4", "Red"))

#Plot for SA (voxels) of BC on hepatocytes

ggplot2::ggplot(dat_24_48) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, BC_SA_Vox, fill = Status1), outlier.color = NA,  size = 1.0, alpha = 0.0, width = 0.4, position = position_dodge(width = 0.7), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = BC_SA_Vox, color = Status1), cex = 2.0, alpha = 0.7, position = position_jitterdodge(0.2,0.2,0.7)) + P +
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = c(0.2,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0)) + ylab("Surface voxels of BC on hepatocytes") + xlab("Timepoint of infection") +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte1.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
#Plot for integrated intensity of BC on hepatocytes
ggplot2::ggplot(dat_24_48_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, BC_int_intensity), outlier.color = NA, size = 1.0, alpha = 0.0, width = 0.4, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = BC_int_intensity, fill = Status), colour = "red", cex = 2.0, alpha = 0.7, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(), panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.position = "none") + ylab("Integrated intensity of BC on PVM") + xlab("Timepoint of infection") +
  ggplot2::ggsave("Int_inten_BC_PVM1.png", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("Int_inten_BC_PVM1.svg", path = "/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/Graphs_SA_vol", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}

#T-test is done here for both salicylate treated and untreated between infected and uninfected cells
dat_24_48_inf <- dat_24_48 %>% dplyr::filter(dat_24_48$Status == "INF")
dat_24_48_uninf <- dat_24_48 %>% dplyr::filter(dat_24_48$Status == "UNINF")


dat_24_inf <- dat_24_48_inf %>% dplyr::filter(dat_24_48_inf$Timepoint == "24hpi")
dat_48_inf <- dat_24_48_inf %>% dplyr::filter(dat_24_48_inf$Timepoint == "48hpi")

dat_24_uninf <- dat_24_48_uninf %>% dplyr::filter(dat_24_48_uninf$Timepoint == "24hpi")
dat_48_uninf <- dat_24_48_uninf %>% dplyr::filter(dat_24_48_uninf$Timepoint == "48hpi")


dat_24_PVM <- dat_24_48_PVM %>% dplyr::filter(dat_24_48_PVM$Timepoint == "24hpi")
dat_48_PVM <- dat_24_48_PVM %>% dplyr::filter(dat_24_48_PVM$Timepoint == "48hpi")
dat_33_PVM <- dat_PVM %>% dplyr::filter(dat_PVM$Timepoint == "33hpi")

dat_33 <- dat %>% dplyr::filter(dat$Timepoint == "33hpi")
dat_33_inf <- dat_33 %>% dplyr::filter(dat_33$Status == "INF")
dat_33_uninf <- dat_33 %>% dplyr::filter(dat_33$Status == "UNINF")




tes_BC_inf_uninf_24 <- t.test(dat_24_inf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), dat_24_uninf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_inf_uninf_48 <- t.test(dat_48_inf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), dat_48_uninf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_int_BC_PVM <- t.test(dat_24_PVM %>% dplyr::select(BC_int_intensity) %>% as.matrix(), dat_48_PVM %>% dplyr::select(BC_int_intensity) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_vol_24 <- t.test(dat_24_inf %>% dplyr::select(Cell_Vol) %>% as.matrix(), dat_24_uninf %>% dplyr::select(Cell_Vol) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_vol_48 <- t.test(dat_48_inf %>% dplyr::select(Cell_Vol) %>% as.matrix(), dat_48_uninf %>% dplyr::select(Cell_Vol) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_vol_33 <- t.test(dat_33_inf %>% dplyr::select(Cell_Vol) %>% as.matrix(), dat_33_uninf %>% dplyr::select(Cell_Vol) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_PVM_33_48 <- t.test(dat_33_PVM %>% dplyr::select(Cell_Surf_Vox) %>% as.matrix(), dat_48_PVM %>% dplyr::select(Cell_Surf_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_PVM_24_33 <- t.test(dat_24_PVM %>% dplyr::select(Cell_Surf_Vox) %>% as.matrix(), dat_33_PVM %>% dplyr::select(Cell_Surf_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

```



