---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
# Intialising the necessary library
library(ggplot2)
library(dplyr)
library(magrittr)
library(svglite)
library(grid)
library(gridExtra)
library(scatterplot3d)
```

```{r}
#Reading the data file
#dat <- readr::read_csv("/home/lab-admin/LAKSHMI/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol/master_data.csv")

dat <- readr::read_csv("/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/SurfaceArea_analysis_new_Jun17/Analysis_SA_vol_24_48/master_data.csv")
#dat$BC_SA_Vox <- dat$BC_SA_Vox/2 #This division by 2 is to consider the voxel just touching the pvm/hepatocytes

dat_33 <- readr::read_csv("/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_vol/master_data.csv")
#dat_33$BC_SA_Vox <- dat_33$BC_SA_Vox*2
colnames(dat_33)[11] <- "Treatment"
dat_33$Timepoint <- "33hpi"
dat_33 <- as.data.frame(sapply(dat_33,gsub,pattern="Ctrl2",replacement="Untreated"))
dat_33 <- as.data.frame(sapply(dat_33,gsub,pattern="Ctrl3",replacement="Untreated"))
dat_33 <- as.data.frame(sapply(dat_33,gsub,pattern="Sal3_",replacement="Treated"))
dat_33 <- as.data.frame(sapply(dat_33,gsub,pattern="Sal2_",replacement="Treated"))
dat_33 <- as.data.frame(sapply(dat_33,gsub,pattern="Sal1_",replacement="Treated"))

dat_33_all <- dat_33

#dat_33$Timepoint_new [grep("Ctrl", dat_33$Timepoint)] <- "33hpi"
dat_33 <- dat_33 %>% dplyr::filter(dat_33$Treatment == "Untreated")  # This is just to consider only salicylate untreated sample from the experiment 6  for 33hpi


dat_33 <- dat_33[,c(1,2,3,4,5,6,7,8,9,10,12)] #copy the column as same as dat dataframe (24 & 48hpi)



dat_24_48 <- dat
dat_24_48 <- na.omit(dat_24_48)
dat_24_48$Treatment <- "Untreated"

dat_33_all <- dat_33_all[,c(1,2,3,4,5,6,7,8,9,10,12,11)]

#Below command is to convert few of the columns from character to numeric
col_name <- c("X1", "Cell_Vol", "Cell_Surf_Vox", "cell_Surf_Pix", "cell_int_intensity", "BC_SA_Pix", "BC_SA_Vox", "BC_int_intensity")
dat_33_all[col_name] <- sapply(dat_33_all[col_name], function(x) as.numeric(as.character(x)))
dat_24_48[col_name] <- sapply(dat_24_48[col_name], function(x) as.numeric(as.character(x)))

#This is the dataframe of all the three timepoints with  and without salicylate treatment & infection
dat_24_33_48 <- rbind(dat_33_all,dat_24_48)

dat_24_33_48_cells <- dat_24_33_48 %>% dplyr::filter(dat_24_33_48$Status != "PVM")

dat_24_33_48_cells$Status_Treat <- "NA"

#This command is to merge strings from two columns with a delimiter
dat_24_33_48_cells$Status_Treat <- paste(dat_24_33_48_cells$Status, dat_24_33_48_cells$Treatment, sep = "_")




dat_24_33_48_cells <- dat_24_33_48_cells %>% dplyr::filter(dat_24_33_48_cells$Timepoint == "33hpi") #only for 33hpi


dat_33[col_name] <- sapply(dat_33[col_name], function(x) as.numeric(as.character(x)))
dat_33$BC_SA_Vox <- dat_33$BC_SA_Vox*4

#This is the dataframe of all the three timepoints without salicylate treatment (Only infection)
dat_all <- rbind(dat,dat_33) # combining both the dataframes

dat_all_new <- na.omit(dat_all) # This is just to remove the rows with NAs. In this case it removed the old 33hpi data which do not have SA on Hepatocyte/PVM

dat_all_new[col_name] <- sapply(dat_all_new[col_name], function(x) as.numeric(as.character(x)))


dat_uninf <- dat_all_new %>% dplyr::filter(dat_all_new$Status == "UNINF")
dat_infec <- dat_all_new %>% dplyr::filter(dat_all_new$Status == "INF")
dat_PVM <- dat_all_new %>% dplyr::filter(dat_all_new$Status == "PVM")

dat_inf_uninf <- rbind(dat_infec, dat_uninf)
dat_inf_PVM <- cbind(dat_infec,dat_PVM) # This is get the infected cell & its corresponding PVM information


# Adding a new column to a dataframe 
dat_inf_PVM["Ratio_Vol_CELL_PVM"] <- 0

# Computing values for new column and adding to it
dat_inf_PVM$Ratio_Vol_CELL_PVM <- round(dat_inf_PVM$Cell_Vol.1/dat_inf_PVM$Cell_Vol,4)

dat_inf_PVM_24 <- dat_inf_PVM %>% dplyr::filter(dat_inf_PVM$Timepoint == "24hpi")


```

```{r}

Status1 <- factor(dat_inf_uninf$Status, levels = c('UNINF','INF'), ordered = TRUE)

#This is to change the color of the jitter points of user's choice
P <- scale_color_manual(dat_inf_uninf$Status,values = c("blue", "Red"))

#Plot for volume of the infected hepatocytes (24,33,48 hpi) (Untreated)

ggplot2::ggplot(dat_inf_uninf) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Cell_Vol, fill = Status1), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Cell_Vol, color = Status1), cex = 2.5, alpha = 0.4, shape = 20, position = position_jitterdodge(0.3,0.3,1.0)) + P + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = c(0.4,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0), legend.text = element_text(size = 6), panel.border = element_blank(), axis.line = element_line()) + ylab("Volume of infected hepatocytes (micron^3)") + xlab("Timepoint of infection") +
  ggplot2::ggsave("volume_inf_hepatocyte_jul18_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_inf_hepatocyte_jul18_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)
  
  
test1 = 0.000567  
ggplot2::ggplot(dat_inf_uninf) +
  ggplot2::geom_boxplot(ggplot2::aes(x = dat_inf_uninf$Timepoint, y = dat_inf_uninf$Cell_Vol, fill = Status1), outlier.shape = NA, notch= FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(x = dat_inf_uninf$Timepoint, y = dat_inf_uninf$Cell_Vol, color = Status1), alpha = 0.75) +
  labs(main = "", x= "", y= expression(paste("Average length of BC ( ", mu, "m)")))+
  theme(
    strip.text = element_text(margin(0,2,0,2), size = rel(1.0)),
    axis.title.x = element_text(margin = margin(0,0,0,0), colour = "gray40", size=rel(1.0)),
    axis.title.y = element_text(margin = margin(0,20,0,0), colour = "gray40", size=rel(1.0), angle=90),
    panel.background = element_rect(fill="white"),
    panel.grid.minor.y = element_line(size=0.5),
    panel.grid.major = element_line(colour = "grey90"),
    panel.grid.minor = element_line(colour = "grey90")
  )  
  
```


```{r}
#Plot for volume of the PVM (24,33,48 hpi) (Untreated)

ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Cell_Vol, fill = Status), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Cell_Vol, fill = Status), colour = "red", alpha= 0.4, cex = 2.5,  shape= 20, position = position_jitterdodge(0.5,0.5,1.0)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = "none", legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0), legend.text = element_text(size = 6), panel.border = element_blank(), axis.line = element_line()) + ylab("Volume of the PVM (micron^3)") + xlab("Timepoint of infection") +
  ggplot2::ggsave("volume_PVM_jul18_new_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_PVM_jul18_new_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol", width = 4, height = 5, units = "in", dpi = 300)

```


```{r}
#Plot for ratio between the pvm and cell volume (Untreated)

scaleFun <- function(x) sprintf("%.2f",x)


ggplot2::ggplot(dat_inf_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, Ratio_Vol_CELL_PVM, fill = Status), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = Ratio_Vol_CELL_PVM, fill = Status), colour = "red", cex = 2.5,  alpha = 0.4, shape = 20, position = position_jitterdodge(0.2,0.2,1.0)) +
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = "none", legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0), legend.text = element_text(size = 6), panel.border = element_blank(), axis.line = element_line()) + ylab("Fraction of PVM in hepatocyte") + xlab("Timepoint of infection") + scale_y_continuous(labels = scaleFun, limits = c(0.00,1.25)) +
  ggplot2::ggsave("volume_ratio_cell_PVM_jul18_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_ratio_cell_PVM_jul18_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

```


```{r}
Status1 <- factor(dat_inf_uninf$Status, levels = c('UNINF','INF'), ordered = TRUE)

#This is to change the color of the jitter points of user's choice
P <- scale_color_manual(dat_inf_uninf$Status,values = c("blue", "Red"))

#Plot for SA (voxels) of BC on hepatocytes (Untreated)

ggplot2::ggplot(dat_inf_uninf) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, BC_SA_Vox, fill = Status1), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = BC_SA_Vox, color = Status1), cex = 2.5, alpha = 0.4, shape = 20, position = position_jitterdodge(0.3,0.3,1.0)) + P + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  scale_x_discrete(expand=c(0,0)) +
  scale_y_continuous(breaks = seq(0,12000,3000)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), legend.title = element_blank(), legend.position = c(0.4,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 1.0), legend.text = element_text(size = 6), panel.border = element_blank(), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Timepoint of infection") +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte_jul18_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte_jul18_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

```


```{r}
#Plot for integrated intensity of BC on hepatocytes (Untreated)
ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_boxplot(ggplot2::aes(Timepoint, BC_SA_Vox), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Timepoint, y = BC_SA_Vox, fill = Status), colour = "red",cex = 2.5, alpha = 0.4, shape = 20, position = position_jitterdodge(0.3,0.3,1.0)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = "none", legend.direction = "horizontal", legend.box.background = element_rect(size = 0.6), legend.text = element_text(size = 5), axis.line = element_line()) + ylab("Surface voxels of BC on PVM") + xlab("Timepoint of infection") +
  ggplot2::ggsave("BC_PVM_jul18_new_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("BC_PVM_jul18_new_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

```

```{r}

#T-test is done here for all three timepoints between infected and uninfected hepatocytes

dat_24 <- dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "24hpi")
dat_24_inf <- dat_24 %>% dplyr::filter(dat_24$Status == "INF")
dat_24_uninf <- dat_24 %>% dplyr::filter(dat_24$Status == "UNINF")


dat_33 <- dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "33hpi")
dat_33_inf <- dat_33 %>% dplyr::filter(dat_33$Status == "INF")
dat_33_uninf <- dat_33 %>% dplyr::filter(dat_33$Status == "UNINF")

dat_48 <- dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "48hpi")
dat_48_inf <- dat_48 %>% dplyr::filter(dat_48$Status == "INF")
dat_48_uninf <- dat_48 %>% dplyr::filter(dat_48$Status == "UNINF")


dat_24_uninf <- dat_24_48_uninf %>% dplyr::filter(dat_24_48_uninf$Timepoint == "24hpi")
dat_48_uninf <- dat_24_48_uninf %>% dplyr::filter(dat_24_48_uninf$Timepoint == "48hpi")


dat_24_PVM <- dat_inf_PVM %>% dplyr::filter(dat_inf_PVM$Timepoint == "24hpi")
dat_48_PVM <- dat_inf_PVM %>% dplyr::filter(dat_inf_PVM$Timepoint == "48hpi")
dat_33_PVM <- dat_inf_PVM %>% dplyr::filter(dat_inf_PVM$Timepoint == "33hpi")

tes_vol_inf_uninf_48 <- t.test(dat_48_inf %>% dplyr::select(Cell_Vol) %>% as.matrix(), dat_48_uninf %>% dplyr::select(Cell_Vol) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_inf_uninf_24 <- t.test(dat_24_inf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), dat_24_uninf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_inf_uninf_33 <- t.test(dat_33_inf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), dat_33_uninf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_inf_uninf_48 <- t.test(dat_48_inf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), dat_48_uninf %>% dplyr::select(BC_SA_Vox) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_PVM_24_33 <- t.test(dat_24_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), dat_33_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_PVM_33_48 <- t.test(dat_33_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), dat_48_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)

tes_BC_PVM_24_48 <- t.test(dat_24_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), dat_48_PVM %>% dplyr::select(Ratio_Vol_CELL_PVM) %>% as.matrix(), alternative = c("two.sided"), paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```

```{r}

#Status_Treat1 <- factor(dat_24_33_48_cells$Status_Treat, levels = c('UNINF_Untreated','INF_Untreated', 'UNINF_Treated','INF_Treated'), ordered = TRUE)
Treatment1 <- factor(dat_24_33_48_cells$Treatment, levels = c('Untreated', 'Treated'), ordered = TRUE)
Status1 <- factor(dat_24_33_48_cells$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
#This is to change the color of the jitter points of user's choice
P <- scale_color_manual(dat_24_33_48_cells$Status,values = c("blue", "Red"))

#Plot for volume of the infected hepatocytes (24,33,48 hpi) (Salicylate treated and untreated; inf & uninfected)

ggplot2::ggplot(dat_24_33_48_cells) +
  ggplot2::geom_boxplot(ggplot2::aes(Treatment1, Cell_Vol, fill = Status1), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Treatment1, y = Cell_Vol, color = Status1), cex = 2.5, alpha = 0.7, position = position_jitterdodge(0.2,0.2,1.0)) + P + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + facet_grid(~Timepoint) +
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.6), legend.text = element_text(size = 5), axis.line = element_line()) + ylab("Volume of infected hepatocytes (micron^3)") + xlab("Timepoint of infection") +
  ggplot2::ggsave("volume_inf_hepatocyte_jul18_sali.png", path = "/media/lab-admin/VS_lab_disk/Lakshmi_working_data/Images_Zstack/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_inf_hepatocyte_jul18_sali.svg", path = "/media/lab-admin/VS_lab_disk/Lakshmi_working_data/Images_Zstack/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

#Plot for SV of BC on hepatocytes (24,33,48 hpi) (Salicylate treated and untreated; inf & uninfected)
ggplot2::ggplot(dat_24_33_48_cells) +
  ggplot2::geom_boxplot(ggplot2::aes(Treatment1, BC_SA_Vox, fill = Status1), outlier.color = NA, size = 0.6, alpha = 0.0, width = 0.6, position = position_dodge(1), varwidth = F, notch = F, outlier.shape = NA, show.legend = FALSE) +
  ggplot2::geom_jitter(ggplot2::aes(Treatment1, y = BC_SA_Vox, color = Status1), cex = 2.5, alpha = 0.4, shape =20, position = position_jitterdodge(0.2,0.2,1.0)) + P + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  scale_x_discrete(expand=c(0,0)) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.2,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.6), legend.text = element_text(size = 4), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Timepoint of infection") +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte_jul18_sali_point.png", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hepatocyte_jul18_sali_point.svg", path = "/Volumes/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)


```

```{r} 
#SA Voxels of BC Vs Volume of hepatocytes
Status1 <- factor(dat_inf_uninf$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf$Cell_Vol, dat_inf_uninf$BC_SA_Vox, color = factor(Status1), shape = factor(dat_inf_uninf$Timepoint)), size =2, alpha = 0.5) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of hepatocytes") +
ggplot2::ggsave("SA_Vox_BC_Vol_hep.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)


dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "24hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of hepatocytes (24hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_24.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_24.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)


dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "33hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+ 
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of hepatocytes (33hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_33.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_33.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)



dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "48hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Vol, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of hepatocytes (48hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_48.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_hep_48.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)


dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "24hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+ 
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Surface voxels of hepatocytes (24hpi)")+
  ggplot2::ggsave("SA_Vox_BC_hep_24.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_24.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "33hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+ 
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Surface voxels of hepatocytes (33hpi)")+
  ggplot2::ggsave("SA_Vox_BC_hep_33.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_33.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

dat_inf_uninf_tmp<-dat_inf_uninf %>% dplyr::filter(dat_inf_uninf$Timepoint == "48hpi")
Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_inf_uninf_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1), size =2, alpha = 0.5)+ 
  ggplot2::geom_smooth(ggplot2::aes(dat_inf_uninf_tmp$Cell_Surf_Vox, dat_inf_uninf_tmp$BC_SA_Vox, color = Status1),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + P + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Surface voxels of hepatocytes (48hpi)")+
  ggplot2::ggsave("SA_Vox_BC_hep_48.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_48.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

write.csv(dat_inf_uninf,file = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/data_all_timepoints.csv")

    dat_inf_uninf_new <- dat_inf_uninf
dat_inf_uninf_new$Timepoint_new <- 0
dat_inf_uninf_new$Timepoint_new <- dat_inf_uninf_new$Timepoint

dat_inf_uninf_new<- as.data.frame(sapply(dat_inf_uninf_new, function(x) gsub("hpi", "", x)))

colors <- c("#999999", "#E69F00", "#56B4E9")
colors <- colors[as.numeric(dat_inf_uninf_new$Timepoint)]
scatterplot3d(x=dat_inf_uninf_new$Cell_Vol, y=dat_inf_uninf_new$BC_SA_Vox, z=dat_inf_uninf_new$Timepoint, color=colors)


```


```{r}
#SA Voxels of BC Vs Volume of PVM
ggplot2::ggplot(dat_PVM) +
  ggplot2::geom_point(ggplot2::aes(dat_PVM$Cell_Vol, dat_PVM$BC_SA_Vox, shape = factor(dat_PVM$Timepoint)), size =3, alpha = 0.6) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "vertical", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on PVM") + xlab("Volume of PVM") +
ggplot2::ggsave("SA_Vox_BC_Vol_PVM.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_PVM_all <- cor.test(dat_PVM$Cell_Vol, dat_PVM$BC_SA_Vox, method = "pearson")


dat_PVM_tmp<-dat_PVM %>% dplyr::filter(dat_PVM$Timepoint == "24hpi")
#Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
#P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_PVM_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox), size =3, alpha = 0.6)+
  ggplot2::geom_smooth(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on PVM") + xlab("Volume of PVM (24hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_24.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_24.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_PVM_BC_24 <- cor.test(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox, method = "pearson")


dat_PVM_tmp<-dat_PVM %>% dplyr::filter(dat_PVM$Timepoint == "33hpi")
#Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
#P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_PVM_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox), size =3, alpha = 0.6)+ 
  ggplot2::geom_smooth(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox),method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on PVM") + xlab("Volume of PVM (33hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_33.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_33.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_PVM_BC_33 <- cor.test(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox, method = "pearson")



dat_PVM_tmp<-dat_PVM %>% dplyr::filter(dat_PVM$Timepoint == "48hpi")
#Status1 <- factor(dat_inf_uninf_tmp$Status, levels = c('UNINF', 'INF'), ordered = TRUE)
#P <- scale_color_manual(dat_inf_uninf_tmp$Status,values = c("blue", "Red"))
ggplot2::ggplot(dat_PVM_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox), size =3, alpha = 0.6)+
  ggplot2::geom_smooth(ggplot2::aes(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox), method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) + 
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.8,0.9), legend.direction = "horizontal", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on PVM") + xlab("Volume of PVM (48hpi)") +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_48.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_Vol_PVM_48.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_PVM_BC_48 <- cor.test(dat_PVM_tmp$Cell_Vol, dat_PVM_tmp$BC_SA_Vox, method = "pearson")

```


```{r}
#SA Voxels of BC on hep Vs Volume of PVM

#dat_PVM_new <- dat_PVM

#col_name_old <- c("X1", "Cell_Vol", "Cell_Surf_Vox", "cell_Surf_Pix", "cell_int_intensity", "BC_SA_Pix", "BC_SA_Vox", "BC_int_intensity", "Status", "File Name", "Timepoint")

#col_name_PVM <- c("X1_PVM", "Cell_Vol_PVM", "Cell_Surf_Vox_PVM", "cell_Surf_Pix_PVM", "cell_int_intensity_PVM", "BC_SA_Pix_PVM", "BC_SA_Vox_PVM", "BC_int_intensity_PVM", "Status_PVM", "File Name_PVM", "Timepoint_PVM")


#dat_PVM_new %>% rename_at(vars(col_name_old), ~col_name_PVM), toupper)

#dat_PVM_new[col_name_PVM] <- sapply(dat_PVM_new[col_name_PVM], function(x) as.numeric(as.character(x)))

dat_hep_PVM <- cbind(dat_inf_PVM,dat_PVM)

write.csv(dat_inf_PVM,file = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/data_hep_PVM.csv")

dat_hep_PVM_n <- readr::read_csv("/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/data_hep_PVM.csv")

dat_hep_PVM_tmp <- dat_hep_PVM_n

ggplot2::ggplot(dat_hep_PVM_tmp) +
  ggplot2::geom_point(ggplot2::aes(dat_hep_PVM_tmp$Cell_Vol_PVM, dat_hep_PVM_tmp$BC_SA_Vox, shape = factor(dat_hep_PVM_tmp$Timepoint)), size =3, alpha = 0.6) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "vertical", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of PVM") +
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_hep_pvm_all <- cor.test(dat_hep_PVM_tmp$Cell_Vol_PVM, dat_hep_PVM_tmp$BC_SA_Vox, method = "pearson")


dat_hep_PVM_tmp_24hpi <- dat_hep_PVM_tmp %>%dplyr::filter(dat_hep_PVM_tmp$Timepoint == "24hpi")
ggplot2::ggplot(dat_hep_PVM_tmp_24hpi) +
  ggplot2::geom_point(ggplot2::aes(dat_hep_PVM_tmp_24hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_24hpi$BC_SA_Vox), size =3, alpha = 0.6) +
  ggplot2::geom_smooth(ggplot2::aes(dat_hep_PVM_tmp_24hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_24hpi$BC_SA_Vox), method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "vertical", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of PVM (24hpi)") + 
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_24hpi.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_24hpi.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_hep_PVM_tmp_24hpi <- cor.test(dat_hep_PVM_tmp_24hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_24hpi$BC_SA_Vox, method = "pearson")


dat_hep_PVM_tmp_33hpi <- dat_hep_PVM_tmp %>%dplyr::filter(dat_hep_PVM_tmp$Timepoint == "33hpi")
ggplot2::ggplot(dat_hep_PVM_tmp_33hpi) +
  ggplot2::geom_point(ggplot2::aes(dat_hep_PVM_tmp_33hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_33hpi$BC_SA_Vox), size =3, alpha = 0.6) +
  ggplot2::geom_smooth(ggplot2::aes(dat_hep_PVM_tmp_33hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_33hpi$BC_SA_Vox), method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "vertical", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of PVM (33hpi)") + 
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_33hpi.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_33hpi.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_hep_PVM_tmp_33hpi <- cor.test(dat_hep_PVM_tmp_33hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_33hpi$BC_SA_Vox, method = "pearson")


dat_hep_PVM_tmp_48hpi <- dat_hep_PVM_tmp %>%dplyr::filter(dat_hep_PVM_tmp$Timepoint == "48hpi")
ggplot2::ggplot(dat_hep_PVM_tmp_48hpi) +
  ggplot2::geom_point(ggplot2::aes(dat_hep_PVM_tmp_48hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_48hpi$BC_SA_Vox), size =3, alpha = 0.6) +
  ggplot2::geom_smooth(ggplot2::aes(dat_hep_PVM_tmp_48hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_48hpi$BC_SA_Vox), method = "lm", se = FALSE) +
  ggplot2::theme_bw()+theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=15, face = "bold"), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank(),panel.grid.minor.x = element_blank(), panel.grid.minor.y = element_blank(), panel.border = element_blank(), legend.title = element_blank(), legend.position = c(0.9,0.9), legend.direction = "vertical", legend.box.background = element_rect(size = 0.1), legend.text = element_text(size = 6), axis.line = element_line()) + ylab("Surface voxels of BC on hepatocytes") + xlab("Volume of PVM (48hpi)") + 
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_48hpi.png", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300) +
  ggplot2::ggsave("SA_Vox_BC_hep_Vol_PVM_48hpi.svg", path = "/media/lakshmi/LAKSHMI2/Lakshmi_working_data_new/Experiment6_images/Analysis_SA_Vol/", width = 4, height = 5, units = "in", dpi = 300)

cor_dat_hep_PVM_tmp_48hpi <- cor.test(dat_hep_PVM_tmp_48hpi$Cell_Vol_PVM, dat_hep_PVM_tmp_48hpi$BC_SA_Vox, method = "pearson")

```
