```{r}
# Intialising the necessary library
library(ggplot2)
library(dplyr)
library(magrittr)
library(svglite)
```

```{r}
dat <- readr::read_csv("/media/lab-admin/data/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/graph_new.csv")
```

```{r}
#Plot for the surface area of BC on infected and uninfected cells between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, SurfaceArea_BC, fill = Status), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.5), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, y = SurfaceArea_BC, color = Status), cex = 0.7, alpha = 0.9, position = position_jitterdodge(0.2,0.2,0.5)) +
  ggplot2::theme_bw() + theme(axis.text = element_text(size=8, colour = "black")) +
  theme(axis.title = element_text(size=10, face = "bold")) + ylab("Surface Area of bile canaliculi on cells (Total number of surface voxels)") +
  ggplot2::ggsave("SA_BC_cells_old.png", path = "I:/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_old_images", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}
#Plot for volume of the infected and uninfected cells between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, Volume, fill = Status), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, y = Volume, fill = Status, color = Status), cex = 0.7, alpha = 0.9, position = position_jitterdodge(0.2,0.2,0.7)) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=20, face = "bold")) + ylab("Volume of infected hepatocytes (micron^3)") +
  ggplot2::ggsave("volume_cells_old.png", path = "/media/lab-admin/data/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_Aug17", width = 8, height = 8, units = "in", dpi = 300) +
  ggplot2::ggsave("volume_cells_old.svg", path = "/media/lab-admin/data/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_Aug17", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
#Plot for surface area of BC on PVM between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, SurfaceArea_BC_PVM), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.5), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, y = SurfaceArea_BC_PVM), cex = 0.9, alpha = 0.9, width = 0.4, height = 0.4) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=8, colour = "black")) +
  theme(axis.title = element_text(size=10, face = "bold")) + ylab("Surface Area of bile canaliculi on PVM (Total number of surface voxels)") +
  ggplot2::ggsave("SA_BC_PVM_old.png", path = "I:/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_old_images", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
#Plot for volume of PVM between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, Volume_PVM), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, Volume_PVM), cex = 0.9, alpha = 0.9, width = 0.2, height = 0.2) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=20, face = "bold")) + ylab("Volume of the PVM (micron^3)") +
  ggplot2::ggsave("Volume_PVM_old.png", path = "/media/lab-admin/data/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_Aug17", width = 8, height = 8, units = "in", dpi = 300)
```


```{r}
#Plot for volume of PVM between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, dat$Fraction_PVM_volume), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.7), varwidth = F, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, dat$Fraction_PVM_volume), cex = 0.9, alpha = 0.9, width = 0.2, height = 0.2) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=14, face = "bold", colour = "black")) +
  theme(axis.title = element_text(size=20, face = "bold")) + ylab("Fraction of PVM on infected hepatocyte") +
  ggplot2::ggsave("fraction_PVM_volume.png", path = "/media/lab-admin/data/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_Aug17", width = 8, height = 8, units = "in", dpi = 300)
```

```{r}
#Plot for percentage of BC only on PVM between 24 and 48hpi
ggplot2::ggplot(dat) +
  ggplot2::geom_boxplot(ggplot2::aes(TimePoint, Percentage_BC_only_PVM), alpha = 0.4, width = 0.5, position = position_dodge(width = 0.5), varwidth = T, notch = F) +
  ggplot2::geom_jitter(ggplot2::aes(TimePoint, y = Percentage_BC_only_PVM), alpha = 0.9, width = 0.4, height = 0.4) + 
  ggplot2::theme_bw() + theme(axis.text = element_text(size=6, colour = "black")) +
  theme(axis.title = element_text(size=10, face = "bold")) + ylab("Percentage of BC only on PVM") +
  ggplot2::ggsave("Percentage_BC_onlyPVM.png", path = "I:/Lakshmi/Surface_area_analysis_seg_editor/Surface_area_results/Graphs_old_images", width = 8, height = 8, units = "in", dpi = 300)
```
```

